### ISSUE TITLE
Do you know how to output a new README?

### ISSUE THREAD

**Issue by wfanad35** [qzhang95/qzhang95.github.io#2]
Hi Mr. ZHANG, I just forked this file and change the content of **_index.html_**, but when I clicked the URL-"https://qzhang95.github.io/" in README part, I found the website content still unchanged and the website content was still your resume. So do you know how to solve this problem?

**Comment by qzhang95** [comment]
Maybe you do not first open your own xxx.github.io homepage.

**Comment by wfanad35** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thanks for reply, I figure it out!
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1142263724
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 5/28/2021 08:51，Qiang ***@***.***> wrote： 



Closed #2.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
